replicaCount: 1

imagePullSecrets:
 - name: acr-secret

image:
  repository: llmretriever.azurecr.io/data-simulator:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: DATABASE_URL
    value: "postgres://mvijdael:tqvh23hSLN51l9UzzOOAoroI9-UZj5c4@raja.db.elephantsql.com/mvijdael"
  - name: RABBITMQ_URL
    value: "amqps://lkwedodk:FKQnL0M20m33KsOwflMGZf0uVqza1c06@beaver.rmq.cloudamqp.com/lkwedodk"