name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Create .env.example file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
        echo "API_PORT=${{ secrets.API_PORT }}" >> .env
        echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> .env

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: llmretriever.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Data Simulator
      uses: docker/build-push-action@v2
      with:
        context: ./data_simulator
        push: true
        tags: llmretriever.azurecr.io/data-simulator:latest

    - name: Build and push Data Retriever
      uses: docker/build-push-action@v2
      with:
        context: ./data_retriever
        push: true
        tags: llmretriever.azurecr.io/data-retriever:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd infrastructure/terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd infrastructure/terraform
        terraform apply -auto-approve
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Set AKS Context
      run: |
        az aks get-credentials --resource-group llm-benchmark-rg --name llm-benchmark-aks --overwrite-existing

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
         version: 'latest'


    - name: Debug Helm
      if: failure()
      run: |
        helm list -A
        helm history data-simulator
        helm history data-retriever

    - name: Get Data Retriever IP
      run: |
        cd infrastructure/terraform
        echo "Data Retriever IP: $(terraform output -raw data_retriever_ip)"