apiVersion: apps/v1
kind: Deployment
imagePullSecrets:
  - name: docker-cfg
metadata:
  name: {{ include "data-simulator.fullname" . }}
  labels:
    {{- include "data-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "data-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-simulator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}